teams:
  - name: lf-staff
    maintainers:
      - ryjones
    members:
      - jwagantall
      - SeanBohan
      - thelinuxfoundation
  - name: otas-maintainers
    maintainers:
      - pv-suren
    members:
      - pv-somyaditya
      - pv-sarvesh
      - MukulKolpe
      - armaanarya
repositories:
  - name: .github
    teams:
      lf-staff: maintain
      otas-maintainers: maintain
    visibility: public
  - name: community-specification-template
    teams:
      lf-staff: maintain
      otas-maintainers: maintain
    visibility: public
  - name: tsc
    teams:
      lf-staff: maintain
      otas-maintainers: maintain
    visibility: public
